const Imagenes = [
  { src: "../../public/GBP.png" },
  { src: "../../public/USD.png" },
  { src: "../../public/CAD.png" },
  { src: "../../public/CHF.png" },
  { src: "../../public/SEK.png" },
  { src: "../../public/NOK.png" },
  { src: "../../public/DKK.png" },
  { src: "../../public/JPY.png" },
  { src: "../../public/AUD.png" },
  { src: "../../public/MAD.png" },
  { src: "../../public/BRL.png" },
  { src: "../../public/MXN.png" },
  { src: "../../public/SAR.png" },
  { src: "../../public/HKD.png" },
  { src: "../../public/NZD.png" },
  { src: "../../public/CZK.png" },
  { src: "../../public/HUF.png" },
  { src: "../../public/ZAR.png" },
  { src: "../../public/SGD.png" },
  { src: "../../public/PLN.png" },
  { src: "../../public/THB.png" },
  { src: "../../public/HRK.png" },
  { src: "../../public/TRY.png" },
  { src: "../../public/CNY.png" },
  { src: "../../public/RUB.png" },
  { src: "../../public/RON.png" },
  { src: "../../public/BGN.png" },
  { src: "../../public/CLP.png" },
  { src: "../../public/AED.png" },
  { src: "../../public/ILS.png" },
];

export default Imagenes;
