import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Breadcrumbs from "@/componentes/Breadcrumbs/Breadcrumbs";
import Section_uno from "@/componentes/Section_1/Section_uno";
import SectionDos from "@/componentes/Section_2/SectionDos";
import SectionTres from "@/componentes/Section_3/SectionTres";
import SectionCuatro from "@/componentes/Section_4/SectionCuatro";
import Mapa from "@/componentes/Mapa/Mapa";
import { arrayTienda } from "../Data";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ dataIdWp, markers }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className={styles.main}>
        <Breadcrumbs />
        <Section_uno />
        <SectionDos />
        <SectionTres />
        <SectionCuatro />
        <Mapa markers={markers} />
      </div>
    </>
  );
}
const idWp = "13848";
export async function getStaticProps() {
  const response = await fetch(
    `https://quickgold.es/wp-json/wp/v2/pages/${idWp}`
  );
  const dataIdWp = await response.json();

  const marker = await fetch(`https://quickgold.es/markers.json`);
  const markers = await marker.json();

  // Pass data to the page via props
  return { props: { dataIdWp, markers }, revalidate: 1 };
}
